---
- name: zabbix_agent
  hosts: "client"
  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled    
    - name: add repo zabbix server 4
      yum:
        name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
        state: present
      when: ansible_distribution == "CentOS" and ansible_distribution_version == '7'
    - name: Installing Zabbix Server
      yum: state=latest name={{ item }}
      with_items:
      - php
      - php-cli
      - php-common
      - php-pear
      - php-gd
      - php-mysql
      - php-xml
      - zabbix-server-mysql
      - zabbix-web-mysql
      - zabbix-java-gateway
      - zabbix-get
    - lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^# DBPassword='
        line: 'DBPassword={{ zabbix_pass }}'
    - lineinfile:
        path: /etc/httpd/conf.d/zabbix.conf
        regexp: '^        # php_value date.timezone Europe/Riga'
        line: '        php_value date.timezone {{ zabbix_timezone }}'
    