global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets.json'

remote_write:
  - url: "http://localhost:8086/api/v1/prom/write?db=prometheus&u=prometheus&p=prometheus"

remote_read:
  - url: "http://localhost:8086/api/v1/prom/read?db=prometheus&u=prometheus&p=prometheus"