---
- name: Install nginx
  hosts: client
  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled
    - name: check status firewalld 
      shell: "firewall-cmd --state"
      register: status
      failed_when:
        - status.rc != 0 
        - status.rc != 252
      when: ansible_distribution == "CentOS" and ansible_distribution_version == '7'
    - name: Firewalld setting 
      firewalld:
        port: 80/tcp
        immediate: yes
        permanent: true
        state: enabled
      when: status.stdout == 'running' and ansible_distribution == "CentOS" and ansible_distribution_version == '7'
    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present
      when: ansible_distribution == "CentOS" and ansible_distribution_version == '7'

    - name: Install nginx
      yum:
        name: nginx
        state: present
      when: ansible_distribution == "CentOS" and ansible_distribution_version == '7'

    - name: Insert Index Page
      template:
        src: index.html
        dest: /usr/share/nginx/html/index.html
      when: ansible_distribution == "CentOS" and ansible_distribution_version == '7'

    - name: Start NGiNX
      service:
        name: nginx
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS" and ansible_distribution_version == '7'
